apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-app
  name: demo-app-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 7123
  selector:
    app: demo-app
  type: NodePort
status:
  loadBalancer: {}
